// Карточки для тренировки. Привязаны к урокам через lessonId.
// Сюда константин будет добавлять карточки для новых уроков —
// с тем же lessonId, что и в lessons.ts.

import type { FlashCard } from '../types';

export const flashCards: FlashCard[] = [
  // Урок 5 — порядок сохранён как в списке константина:
  // слово → сочетание → фраза с ним, по темам.
  { id: 'l5-01', lessonId: 'lesson-5', vi: 'bạn', ru: 'друг; ты (обращение)' },
  { id: 'l5-02', lessonId: 'lesson-5', vi: 'bạn thân', ru: 'близкий друг' },
  { id: 'l5-03', lessonId: 'lesson-5', vi: 'các bạn', ru: 'друзья; вы (обращение к группе)' },
  { id: 'l5-04', lessonId: 'lesson-5', vi: 'Xin chào các bạn.', ru: 'Здравствуйте, друзья.' },
  { id: 'l5-05', lessonId: 'lesson-5', vi: 'vợ', ru: 'жена' },
  { id: 'l5-06', lessonId: 'lesson-5', vi: 'vợ anh', ru: 'моя жена (если говорящий называет себя anh)' },
  { id: 'l5-07', lessonId: 'lesson-5', vi: 'đây', ru: 'здесь; это (при указании)' },
  { id: 'l5-08', lessonId: 'lesson-5', vi: 'Đây là vợ anh.', ru: 'Это моя жена.' },
  { id: 'l5-09', lessonId: 'lesson-5', vi: 'Còn đây là…', ru: 'А это…' },
  { id: 'l5-10', lessonId: 'lesson-5', vi: 'anh ấy', ru: 'он' },
  { id: 'l5-11', lessonId: 'lesson-5', vi: 'Anh ấy tên là gì?', ru: 'Как его зовут?' },
  { id: 'l5-12', lessonId: 'lesson-5', vi: 'cô ấy', ru: 'она' },
  { id: 'l5-13', lessonId: 'lesson-5', vi: 'Cô ấy tên là gì?', ru: 'Как её зовут?' },
  { id: 'l5-14', lessonId: 'lesson-5', vi: 'và', ru: 'и' },
  { id: 'l5-15', lessonId: 'lesson-5', vi: 'Tôi và cô ấy là bạn thân.', ru: 'Мы с ней близкие друзья.' },
  {
    id: 'l5-16',
    lessonId: 'lesson-5',
    vi: 'nghề',
    ru: 'профессия',
    imageUrl: `${import.meta.env.BASE_URL}images/cards/nghe.png`,
  },
  {
    id: 'l5-17',
    lessonId: 'lesson-5',
    vi: 'làm',
    ru: 'делать; работать',
    imageUrl: `${import.meta.env.BASE_URL}images/cards/lam.jpg`,
  },
  {
    id: 'l5-17a',
    lessonId: 'lesson-5',
    vi: 'việc',
    ru: 'дело',
    imageUrl: `${import.meta.env.BASE_URL}images/cards/viec.jpg`,
  },
  { id: 'l5-18', lessonId: 'lesson-5', vi: 'làm nghề gì?', ru: 'кем работать? / какая профессия?' },
  { id: 'l5-19', lessonId: 'lesson-5', vi: 'Anh ấy làm nghề gì?', ru: 'Кем он работает?' },
  { id: 'l5-20', lessonId: 'lesson-5', vi: 'Cô ấy làm nghề gì?', ru: 'Кем она работает?' },
  { id: 'l5-21', lessonId: 'lesson-5', vi: 'kĩ sư / kỹ sư', ru: 'инженер' },
  { id: 'l5-22', lessonId: 'lesson-5', vi: 'Tôi là kĩ sư.', ru: 'Я инженер.' },
  {
    id: 'l5-23',
    lessonId: 'lesson-5',
    vi: 'giáo viên',
    ru: 'учитель',
    imageUrl: `${import.meta.env.BASE_URL}images/cards/giao-vien.jpg`,
  },
  { id: 'l5-24', lessonId: 'lesson-5', vi: 'Cô ấy là giáo viên.', ru: 'Она учитель.' },
  { id: 'l5-25', lessonId: 'lesson-5', vi: 'sinh viên', ru: 'студент' },
  { id: 'l5-26', lessonId: 'lesson-5', vi: 'thư ký', ru: 'секретарь' },
  { id: 'l5-27', lessonId: 'lesson-5', vi: 'bác sĩ', ru: 'врач' },
  { id: 'l5-28', lessonId: 'lesson-5', vi: 'tài xế', ru: 'водитель' },
  { id: 'l5-29', lessonId: 'lesson-5', vi: 'lái xe', ru: 'водить машину' },
  {
    id: 'l5-30',
    lessonId: 'lesson-5',
    vi: 'làm việc',
    ru: 'работать',
    imageUrl: `${import.meta.env.BASE_URL}images/cards/lam-viec.jpg`,
  },
  {
    id: 'l5-30a',
    lessonId: 'lesson-5',
    vi: 'công việc',
    ru: 'работа',
    imageUrl: `${import.meta.env.BASE_URL}images/cards/cong-viec.png`,
  },
  { id: 'l5-31', lessonId: 'lesson-5', vi: 'công ty', ru: 'компания' },
  { id: 'l5-32', lessonId: 'lesson-5', vi: 'Tôi làm việc ở công ty.', ru: 'Я работаю в компании.' },
  {
    id: 'l5-33',
    lessonId: 'lesson-5',
    vi: 'xây dựng',
    ru: 'строительство; строить',
    imageUrl: `${import.meta.env.BASE_URL}images/cards/xay-dung.jpg`,
  },
  { id: 'l5-34', lessonId: 'lesson-5', vi: 'công ty xây dựng', ru: 'строительная компания' },
  { id: 'l5-35', lessonId: 'lesson-5', vi: 'đâu', ru: 'где (в вопросах)' },
  { id: 'l5-36', lessonId: 'lesson-5', vi: 'ở đâu?', ru: 'где?' },
  { id: 'l5-37', lessonId: 'lesson-5', vi: 'Cô ấy làm việc ở đâu?', ru: 'Где она работает?' },
  { id: 'l5-38', lessonId: 'lesson-5', vi: 'học', ru: 'учиться' },
  {
    id: 'l5-39',
    lessonId: 'lesson-5',
    vi: 'trường',
    ru: 'школа; учебное заведение',
    imageUrl: `${import.meta.env.BASE_URL}images/cards/truong.jpg`,
  },
  { id: 'l5-40', lessonId: 'lesson-5', vi: 'trường đại học', ru: 'университет' },
  { id: 'l5-41', lessonId: 'lesson-5', vi: 'Anh ấy học ở đâu?', ru: 'Где он учится?' },

  // Урок 4 — порядок сохранён как в списке константина.
  // В исходном списке несколько номеров были пропущены или помечены
  // «.» без содержимого — они просто не перенесены, нумерация карточек
  // здесь сквозная, без разрывов.
  { id: 'l4-01', lessonId: 'lesson-4', vi: 'đã', ru: 'показатель прошедшего действия' },
  { id: 'l4-02', lessonId: 'lesson-4', vi: 'đang', ru: 'показатель действия, происходящего сейчас' },
  { id: 'l4-03', lessonId: 'lesson-4', vi: 'sẽ', ru: 'показатель будущего действия' },
  { id: 'l4-04', lessonId: 'lesson-4', vi: 'rồi', ru: 'уже; обозначает завершение или изменение ситуации' },
  {
    id: 'l4-05',
    lessonId: 'lesson-4',
    vi: 'ngày mai',
    ru: 'завтра',
    imageUrl: `${import.meta.env.BASE_URL}images/cards/ngay-mai.png`,
  },
  { id: 'l4-06', lessonId: 'lesson-4', vi: 'giờ', ru: 'час; время' },
  { id: 'l4-07', lessonId: 'lesson-4', vi: 'Anh đã uống cà phê.', ru: 'Я пил кофе.' },
  { id: 'l4-08', lessonId: 'lesson-4', vi: 'Anh đang uống cà phê.', ru: 'Я сейчас пью кофе.' },
  { id: 'l4-09', lessonId: 'lesson-4', vi: 'Ngày mai anh sẽ uống cà phê.', ru: 'Завтра я буду пить кофе.' },
  { id: 'l4-10', lessonId: 'lesson-4', vi: 'đi Cam Ranh', ru: 'ехать в Камрань' },
  { id: 'l4-11', lessonId: 'lesson-4', vi: 'Anh đã đi Cam Ranh.', ru: 'Я ездил в Камрань.' },
  { id: 'l4-12', lessonId: 'lesson-4', vi: 'Anh đã đi Mũi Né rồi.', ru: 'Я уже ездил в Муйне.' },
  { id: 'l4-13', lessonId: 'lesson-4', vi: 'Ngày mai anh sẽ đi Cam Ranh.', ru: 'Завтра я поеду в Камрань.' },
  {
    id: 'l4-14',
    lessonId: 'lesson-4',
    vi: 'Chị sẽ đi An Viên vào ngày mai.',
    ru: 'Вы поедете в Ан Вьен завтра (обращение к женщине).',
  },
  { id: 'l4-15', lessonId: 'lesson-4', vi: 'đi chợ', ru: 'идти на рынок' },
  { id: 'l4-16', lessonId: 'lesson-4', vi: 'Anh đang đi chợ.', ru: 'Я сейчас иду на рынок.' },
  { id: 'l4-17', lessonId: 'lesson-4', vi: 'ăn', ru: 'есть; кушать' },
  { id: 'l4-18', lessonId: 'lesson-4', vi: 'ăn phở bò', ru: 'есть фо бо' },
  { id: 'l4-19', lessonId: 'lesson-4', vi: 'Anh đã ăn phở bò.', ru: 'Я ел фо бо.' },
  { id: 'l4-20', lessonId: 'lesson-4', vi: 'ăn cơm', ru: 'есть рис; есть, принимать пищу' },
  { id: 'l4-21', lessonId: 'lesson-4', vi: 'Anh đang ăn cơm.', ru: 'Я сейчас ем.' },
  { id: 'l4-22', lessonId: 'lesson-4', vi: 'Ngày mai anh sẽ ăn phở bò.', ru: 'Завтра я буду есть фо бо.' },
  { id: 'l4-23', lessonId: 'lesson-4', vi: 'thích', ru: 'любить; нравиться' },
  { id: 'l4-24', lessonId: 'lesson-4', vi: 'xe máy', ru: 'мотобайк; мотоцикл' },
  { id: 'l4-25', lessonId: 'lesson-4', vi: 'Anh thích xe máy.', ru: 'Мне нравятся мотобайки.' },
  { id: 'l4-26', lessonId: 'lesson-4', vi: 'học tiếng Việt', ru: 'учить вьетнамский язык' },
  { id: 'l4-27', lessonId: 'lesson-4', vi: 'Anh muốn học tiếng Việt.', ru: 'Я хочу учить вьетнамский.' },
  { id: 'l4-28', lessonId: 'lesson-4', vi: 'Anh đang học tiếng Việt.', ru: 'Я сейчас учу вьетнамский.' },
  { id: 'l4-29', lessonId: 'lesson-4', vi: 'mua', ru: 'покупать' },
  { id: 'l4-30', lessonId: 'lesson-4', vi: 'mua xe máy', ru: 'покупать мотобайк' },
  { id: 'l4-31', lessonId: 'lesson-4', vi: 'Anh muốn mua xe máy.', ru: 'Я хочу купить мотобайк.' },
  { id: 'l4-32', lessonId: 'lesson-4', vi: 'quà', ru: 'подарок' },
  { id: 'l4-33', lessonId: 'lesson-4', vi: 'mua quà', ru: 'покупать подарок' },
  { id: 'l4-34', lessonId: 'lesson-4', vi: 'Anh đang mua quà.', ru: 'Я сейчас покупаю подарок.' },
  { id: 'l4-35', lessonId: 'lesson-4', vi: 'Ngày mai anh sẽ mua quà.', ru: 'Завтра я куплю подарок.' },
  { id: 'l4-36', lessonId: 'lesson-4', vi: 'nghề nghiệp', ru: 'профессия' },
  { id: 'l4-37', lessonId: 'lesson-4', vi: 'bác sĩ', ru: 'врач' },
  { id: 'l4-38', lessonId: 'lesson-4', vi: 'y tá', ru: 'медсестра; медбрат' },
  { id: 'l4-39', lessonId: 'lesson-4', vi: 'giám đốc', ru: 'директор' },
  { id: 'l4-40', lessonId: 'lesson-4', vi: 'thư ký', ru: 'секретарь' },
  { id: 'l4-41', lessonId: 'lesson-4', vi: 'sếp', ru: 'начальник; босс' },
  {
    id: 'l4-42',
    lessonId: 'lesson-4',
    vi: 'nhân viên',
    ru: 'сотрудник',
    imageUrl: `${import.meta.env.BASE_URL}images/cards/nhan-vien.png`,
  },
  { id: 'l4-43', lessonId: 'lesson-4', vi: 'quản lý', ru: 'менеджер; управляющий' },
  { id: 'l4-44', lessonId: 'lesson-4', vi: 'công an', ru: 'полиция; сотрудник полиции' },
  { id: 'l4-45', lessonId: 'lesson-4', vi: 'cảnh sát', ru: 'полиция; полицейский' },
  {
    id: 'l4-46',
    lessonId: 'lesson-4',
    vi: 'cảnh sát giao thông',
    ru: 'дорожная полиция; сотрудник дорожной полиции',
  },
  {
    id: 'l4-47',
    lessonId: 'lesson-4',
    vi: 'giáo viên',
    ru: 'учитель',
    imageUrl: `${import.meta.env.BASE_URL}images/cards/giao-vien.jpg`,
  },
  { id: 'l4-48', lessonId: 'lesson-4', vi: 'sinh viên', ru: 'студент' },
  {
    id: 'l4-49',
    lessonId: 'lesson-4',
    vi: 'cô giáo',
    ru: 'учительница',
    imageUrl: `${import.meta.env.BASE_URL}images/cards/co-giao.png`,
  },
  {
    id: 'l4-50',
    lessonId: 'lesson-4',
    vi: 'thầy giáo',
    ru: 'учитель-мужчина',
    imageUrl: `${import.meta.env.BASE_URL}images/cards/thay-giao.jpg`,
  },
  { id: 'l4-51', lessonId: 'lesson-4', vi: 'kỹ sư', ru: 'инженер' },
  { id: 'l4-52', lessonId: 'lesson-4', vi: 'làm nghề gì?', ru: 'кем работать? / какая профессия?' },
  { id: 'l4-53', lessonId: 'lesson-4', vi: 'Anh làm nghề gì?', ru: 'Кем ты работаешь?' },
  { id: 'l4-54', lessonId: 'lesson-4', vi: 'Anh Mikhail là kỹ sư.', ru: 'Михаил — инженер.' },
  { id: 'l4-55', lessonId: 'lesson-4', vi: 'Chị là y tá.', ru: 'Вы медсестра (обращение к женщине).' },
  { id: 'l4-56', lessonId: 'lesson-4', vi: 'làm việc', ru: 'работать' },
  { id: 'l4-57', lessonId: 'lesson-4', vi: 'làm việc ở đâu?', ru: 'где работать?' },
  { id: 'l4-58', lessonId: 'lesson-4', vi: 'Anh làm việc ở đâu?', ru: 'Где ты работаешь?' },
  { id: 'l4-59', lessonId: 'lesson-4', vi: 'ở đâu?', ru: 'где?' },
  { id: 'l4-60', lessonId: 'lesson-4', vi: 'công ty', ru: 'компания' },
  { id: 'l4-61', lessonId: 'lesson-4', vi: 'Công ty ở đâu?', ru: 'Где находится компания?' },
  { id: 'l4-62', lessonId: 'lesson-4', vi: 'Tôi là nhân viên công ty.', ru: 'Я сотрудник компании.' },
  { id: 'l4-63', lessonId: 'lesson-4', vi: 'bệnh viện', ru: 'больница' },
  { id: 'l4-64', lessonId: 'lesson-4', vi: 'Bệnh viện ở đâu?', ru: 'Где находится больница?' },
  {
    id: 'l4-65',
    lessonId: 'lesson-4',
    vi: 'Chị làm việc ở bệnh viện.',
    ru: 'Вы работаете в больнице (обращение к женщине).',
  },
  { id: 'l4-66', lessonId: 'lesson-4', vi: 'nhà hàng', ru: 'ресторан' },
  { id: 'l4-67', lessonId: 'lesson-4', vi: 'Nhà hàng ở đâu?', ru: 'Где находится ресторан?' },
  {
    id: 'l4-68',
    lessonId: 'lesson-4',
    vi: 'trường',
    ru: 'школа; учебное заведение',
    imageUrl: `${import.meta.env.BASE_URL}images/cards/truong.jpg`,
  },
  { id: 'l4-69', lessonId: 'lesson-4', vi: 'trường đại học', ru: 'университет' },
  { id: 'l4-70', lessonId: 'lesson-4', vi: 'Trường đại học ở đâu?', ru: 'Где находится университет?' },
  { id: 'l4-71', lessonId: 'lesson-4', vi: 'Còn em?', ru: 'А ты?' },
  { id: 'l4-72', lessonId: 'lesson-4', vi: 'Còn em thế nào?', ru: 'А ты как?' },
  { id: 'l4-73', lessonId: 'lesson-4', vi: 'cũng', ru: 'тоже; также' },
  { id: 'l4-74', lessonId: 'lesson-4', vi: 'khỏe', ru: 'здоровый; хорошо себя чувствующий' },
  { id: 'l4-75', lessonId: 'lesson-4', vi: 'Anh cũng khỏe.', ru: 'Я тоже здоров.' },
  {
    id: 'l4-76',
    lessonId: 'lesson-4',
    vi: 'Em cũng vậy.',
    ru: 'Я тоже; у меня так же (говорящий называет себя em).',
  },
  {
    id: 'l4-77',
    lessonId: 'lesson-4',
    vi: 'Chị sẽ đi Đà Lạt.',
    ru: 'Вы поедете в Далат (обращение к женщине).',
  },

  // Урок 3 — порядок сохранён как в списке константина.
  { id: 'l3-01', lessonId: 'lesson-3', vi: 'tên', ru: 'имя' },
  { id: 'l3-02', lessonId: 'lesson-3', vi: 'gì', ru: 'что; какой (в вопросах)' },
  { id: 'l3-03', lessonId: 'lesson-3', vi: 'làm quen', ru: 'знакомиться' },
  { id: 'l3-04', lessonId: 'lesson-3', vi: 'Anh tên là gì?', ru: 'Как тебя зовут? (обращение к мужчине).' },
  {
    id: 'l3-05',
    lessonId: 'lesson-3',
    vi: 'Em tên là gì?',
    ru: 'Как тебя зовут? (обращение к младшему собеседнику любого пола).',
  },
  { id: 'l3-06', lessonId: 'lesson-3', vi: 'Bạn tên là gì?', ru: 'Как тебя зовут? (нейтральное обращение).' },
  { id: 'l3-07', lessonId: 'lesson-3', vi: 'Anh tên là Kostya.', ru: 'Меня зовут Костя.' },
  {
    id: 'l3-08',
    lessonId: 'lesson-3',
    vi: 'Em tên là Alex.',
    ru: 'Меня зовут Алекс (говорящий называет себя em).',
  },
  { id: 'l3-09', lessonId: 'lesson-3', vi: 'Rất vui được làm quen.', ru: 'Очень приятно познакомиться.' },
  {
    id: 'l3-10',
    lessonId: 'lesson-3',
    vi: 'Rất vui được gặp anh.',
    ru: 'Очень рад встрече с тобой (обращение к мужчине).',
  },
  {
    id: 'l3-11',
    lessonId: 'lesson-3',
    vi: 'Rất vui được gặp em.',
    ru: 'Очень рад встрече с тобой (обращение к младшему).',
  },
  { id: 'l3-12', lessonId: 'lesson-3', vi: 'khỏe', ru: 'здоровый; хорошо себя чувствующий' },
  { id: 'l3-13', lessonId: 'lesson-3', vi: 'không khỏe', ru: 'нездоровый; плохо себя чувствующий' },
  { id: 'l3-14', lessonId: 'lesson-3', vi: 'bình thường', ru: 'нормально; обычный' },
  { id: 'l3-15', lessonId: 'lesson-3', vi: 'cảm ơn', ru: 'спасибо' },
  {
    id: 'l3-16',
    lessonId: 'lesson-3',
    vi: 'Anh có khỏe không?',
    ru: 'Как твоё здоровье? (обращение к мужчине).',
  },
  {
    id: 'l3-17',
    lessonId: 'lesson-3',
    vi: 'Em có khỏe không?',
    ru: 'Как твоё здоровье? (обращение к младшему).',
  },
  { id: 'l3-18', lessonId: 'lesson-3', vi: 'Bạn khỏe không?', ru: 'Как ты? / Как твоё здоровье?' },
  { id: 'l3-19', lessonId: 'lesson-3', vi: 'Có, anh khỏe.', ru: 'Да, я здоров.' },
  {
    id: 'l3-20',
    lessonId: 'lesson-3',
    vi: 'Không, anh không khỏe.',
    ru: 'Нет, я нездоров (говорящий называет себя anh).',
  },
  {
    id: 'l3-21',
    lessonId: 'lesson-3',
    vi: 'Không, em không khỏe.',
    ru: 'Нет, я нездоров / нездорова (говорящий называет себя em).',
  },
  { id: 'l3-22', lessonId: 'lesson-3', vi: 'Anh bình thường.', ru: 'У меня всё нормально.' },
  { id: 'l3-23', lessonId: 'lesson-3', vi: 'Cảm ơn, anh khỏe.', ru: 'Спасибо, я здоров.' },
  {
    id: 'l3-24',
    lessonId: 'lesson-3',
    vi: 'còn',
    ru: 'а; что касается… (при переходе к другому человеку или предмету)',
    imageUrl: `${import.meta.env.BASE_URL}images/cards/con.png`,
  },
  {
    id: 'l3-25',
    lessonId: 'lesson-3',
    vi: 'thế nào',
    ru: 'как?',
    imageUrl: `${import.meta.env.BASE_URL}images/cards/the-nao.png`,
  },
  { id: 'l3-28', lessonId: 'lesson-3', vi: 'Còn em?', ru: 'А ты?' },
  { id: 'l3-29', lessonId: 'lesson-3', vi: 'Còn em thế nào?', ru: 'А ты как?' },
  { id: 'l3-26', lessonId: 'lesson-3', vi: 'cũng', ru: 'тоже; также' },
  { id: 'l3-27', lessonId: 'lesson-3', vi: 'vậy', ru: 'так' },
  {
    id: 'l3-30',
    lessonId: 'lesson-3',
    vi: 'Anh cũng khỏe.',
    ru: 'Я тоже здоров (говорящий называет себя anh).',
  },
  {
    id: 'l3-31',
    lessonId: 'lesson-3',
    vi: 'Em cũng khỏe.',
    ru: 'Я тоже здоров / здорова (говорящий называет себя em).',
  },
  { id: 'l3-32', lessonId: 'lesson-3', vi: 'Em cũng vậy.', ru: 'Я тоже; у меня так же.' },
  { id: 'l3-33', lessonId: 'lesson-3', vi: 'uống', ru: 'пить' },
  { id: 'l3-34', lessonId: 'lesson-3', vi: 'cà phê', ru: 'кофе' },
  { id: 'l3-35', lessonId: 'lesson-3', vi: 'uống cà phê', ru: 'пить кофе' },
  { id: 'l3-36', lessonId: 'lesson-3', vi: 'Em có uống cà phê không?', ru: 'Ты пьёшь кофе?' },
  { id: 'l3-37', lessonId: 'lesson-3', vi: 'đi', ru: 'идти; ехать' },
  { id: 'l3-38', lessonId: 'lesson-3', vi: 'đi Cam Ranh', ru: 'ехать в Камрань' },
  { id: 'l3-39', lessonId: 'lesson-3', vi: 'Em có đi Cam Ranh không?', ru: 'Ты едешь в Камрань?' },
  { id: 'l3-40', lessonId: 'lesson-3', vi: 'ăn', ru: 'есть; кушать' },
  { id: 'l3-41', lessonId: 'lesson-3', vi: 'phở bò', ru: 'фо бо, суп с говядиной' },
  { id: 'l3-42', lessonId: 'lesson-3', vi: 'ăn phở bò', ru: 'есть фо бо' },
  { id: 'l3-43', lessonId: 'lesson-3', vi: 'muốn', ru: 'хотеть' },
  { id: 'l3-44', lessonId: 'lesson-3', vi: 'muốn ăn', ru: 'хотеть есть' },
  {
    id: 'l3-45',
    lessonId: 'lesson-3',
    vi: 'Em có muốn ăn phở bò không?',
    ru: 'Ты хочешь поесть фо бо?',
  },
  { id: 'l3-46', lessonId: 'lesson-3', vi: 'thích', ru: 'любить; нравиться' },
  { id: 'l3-47', lessonId: 'lesson-3', vi: 'chơi', ru: 'играть' },
  { id: 'l3-48', lessonId: 'lesson-3', vi: 'chơi pickleball', ru: 'играть в пиклбол' },
  { id: 'l3-49', lessonId: 'lesson-3', vi: 'thích chơi pickleball', ru: 'любить играть в пиклбол' },
  { id: 'l3-50', lessonId: 'lesson-3', vi: 'xe máy', ru: 'мотобайк; мотоцикл' },
  { id: 'l3-51', lessonId: 'lesson-3', vi: 'Anh thích xe máy.', ru: 'Мне нравятся мотобайки.' },
  { id: 'l3-52', lessonId: 'lesson-3', vi: 'mua', ru: 'покупать' },
  { id: 'l3-53', lessonId: 'lesson-3', vi: 'mua xe máy', ru: 'покупать мотобайк' },
  { id: 'l3-54', lessonId: 'lesson-3', vi: 'muốn mua', ru: 'хотеть купить' },
  { id: 'l3-55', lessonId: 'lesson-3', vi: 'muốn mua xe máy', ru: 'хотеть купить мотобайк' },
  { id: 'l3-56', lessonId: 'lesson-3', vi: 'Em có mua xe máy không?', ru: 'Ты покупаешь мотобайк?' },

  // Урок 2 — порядок сохранён как в списке константина.
  { id: 'l2-01', lessonId: 'lesson-2', vi: 'tôi', ru: 'я (нейтрально)' },
  {
    id: 'l2-02',
    lessonId: 'lesson-2',
    vi: 'anh',
    ru: 'старший брат; обращение к мужчине немного старше или примерно своего возраста',
  },
  {
    id: 'l2-03',
    lessonId: 'lesson-2',
    vi: 'chị',
    ru: 'старшая сестра; обращение к женщине немного старше или примерно своего возраста',
  },
  {
    id: 'l2-04',
    lessonId: 'lesson-2',
    vi: 'em',
    ru: 'младший брат или сестра; обращение к младшему собеседнику любого пола',
  },
  {
    id: 'l2-05',
    lessonId: 'lesson-2',
    vi: 'bạn',
    ru: 'друг; ты (нейтральное обращение, часто к ровеснику)',
  },
  { id: 'l2-06', lessonId: 'lesson-2', vi: 'ông', ru: 'дедушка; уважительное обращение к пожилому мужчине' },
  { id: 'l2-07', lessonId: 'lesson-2', vi: 'bà', ru: 'бабушка; уважительное обращение к пожилой женщине' },
  {
    id: 'l2-08',
    lessonId: 'lesson-2',
    vi: 'bác',
    ru: 'дядя или тётя; уважительное обращение к человеку поколения родителей, обычно старше них',
  },
  {
    id: 'l2-09',
    lessonId: 'lesson-2',
    vi: 'chú',
    ru: 'дядя; обращение к мужчине поколения родителей, обычно младше отца',
  },
  {
    id: 'l2-10',
    lessonId: 'lesson-2',
    vi: 'cô',
    ru: 'тётя; учительница; обращение к женщине поколения родителей',
  },
  {
    id: 'l2-11',
    lessonId: 'lesson-2',
    vi: 'cụ',
    ru: 'прадедушка или прабабушка; уважительное обращение к очень пожилому человеку',
  },
  {
    id: 'l2-12',
    lessonId: 'lesson-2',
    vi: 'cháu',
    ru: 'внук, внучка, племянник или племянница; обращение к человеку значительно младше',
  },
  { id: 'l2-13', lessonId: 'lesson-2', vi: 'con', ru: 'ребёнок; сын или дочь' },
  { id: 'l2-14', lessonId: 'lesson-2', vi: 'bé', ru: 'малыш; малышка' },
  {
    id: 'l2-15',
    lessonId: 'lesson-2',
    vi: 'cậu',
    ru: 'дядя по матери; дружеское «ты» среди ровесников',
  },
  { id: 'l2-16', lessonId: 'lesson-2', vi: 'mợ', ru: 'жена дяди по матери; семейное обращение' },
  { id: 'l2-17', lessonId: 'lesson-2', vi: 'ông ấy', ru: 'он (о пожилом мужчине)' },
  { id: 'l2-18', lessonId: 'lesson-2', vi: 'bà ấy', ru: 'она (о пожилой женщине)' },
  { id: 'l2-19', lessonId: 'lesson-2', vi: 'anh ấy', ru: 'он (о мужчине)' },
  { id: 'l2-20', lessonId: 'lesson-2', vi: 'chị ấy', ru: 'она (о женщине)' },
  { id: 'l2-21', lessonId: 'lesson-2', vi: 'em ấy', ru: 'он или она (о младшем человеке)' },
  { id: 'l2-22', lessonId: 'lesson-2', vi: 'ơi', ru: 'частица для привлечения внимания при обращении' },
  { id: 'l2-23', lessonId: 'lesson-2', vi: 'ạ', ru: 'частица вежливости, обычно в конце фразы' },
  { id: 'l2-24', lessonId: 'lesson-2', vi: 'này', ru: 'этот; эй, послушай (в обращении)' },
  { id: 'l2-25', lessonId: 'lesson-2', vi: 'và', ru: 'и' },
  { id: 'l2-26', lessonId: 'lesson-2', vi: 'với', ru: 'с' },
  { id: 'l2-27', lessonId: 'lesson-2', vi: 'cũng', ru: 'тоже; также' },
  { id: 'l2-28', lessonId: 'lesson-2', vi: 'Anh ơi!', ru: 'Извините! / Можно вас? (к мужчине).' },
  { id: 'l2-29', lessonId: 'lesson-2', vi: 'Chị ơi!', ru: 'Извините! / Можно вас? (к женщине).' },
  { id: 'l2-30', lessonId: 'lesson-2', vi: 'Em ơi!', ru: 'Можно тебя? (к младшему).' },
  { id: 'l2-31', lessonId: 'lesson-2', vi: 'Bác ơi!', ru: 'Извините! / Можно вас? (к старшему).' },
  { id: 'l2-32', lessonId: 'lesson-2', vi: 'Mẹ ơi!', ru: 'Мама! (позвать маму).' },
  { id: 'l2-33', lessonId: 'lesson-2', vi: 'Tôi là Kosta.', ru: 'Я Костя.' },

  // Урок 6 — порядок сохранён как в списке константина.
  { id: 'l6-01', lessonId: 'lesson-6', vi: 'phải không?', ru: 'верно? / не так ли?' },
  { id: 'l6-02', lessonId: 'lesson-6', vi: 'đúng không?', ru: 'правильно? / верно?' },
  { id: 'l6-03', lessonId: 'lesson-6', vi: '... à?', ru: 'вопросительное уточнение: «Так ...?»' },
  { id: 'l6-04', lessonId: 'lesson-6', vi: 'có phải là ... không?', ru: 'является ли ...?' },
  {
    id: 'l6-05',
    lessonId: 'lesson-6',
    vi: 'không phải là',
    ru: 'не является; не ... (перед профессией или ролью)',
  },
  { id: 'l6-06', lessonId: 'lesson-6', vi: 'Vâng.', ru: 'Да (вежливо).' },
  { id: 'l6-07', lessonId: 'lesson-6', vi: 'Đúng.', ru: 'Верно.' },
  { id: 'l6-08', lessonId: 'lesson-6', vi: 'Phải.', ru: 'Да, верно.' },
  { id: 'l6-09', lessonId: 'lesson-6', vi: 'Ừ.', ru: 'Угу; да (неформально).' },
  { id: 'l6-10', lessonId: 'lesson-6', vi: 'Không.', ru: 'Нет.' },
  { id: 'l6-11', lessonId: 'lesson-6', vi: 'Vâng, đúng rồi.', ru: 'Да, верно.' },
  {
    id: 'l6-12',
    lessonId: 'lesson-6',
    vi: 'Anh Artur là bác sĩ, phải không?',
    ru: 'Артур — врач, верно?',
  },
  {
    id: 'l6-13',
    lessonId: 'lesson-6',
    vi: 'Anh Artur là bác sĩ, đúng không?',
    ru: 'Артур — врач, правильно?',
  },
  { id: 'l6-14', lessonId: 'lesson-6', vi: 'Anh Artur là bác sĩ à?', ru: 'Так Артур — врач?' },
  {
    id: 'l6-15',
    lessonId: 'lesson-6',
    vi: 'Em thích uống cà phê, phải không?',
    ru: 'Ты любишь пить кофе, верно?',
  },
  { id: 'l6-16', lessonId: 'lesson-6', vi: 'Anh Artur có phải là bác sĩ không?', ru: 'Артур — врач?' },
  { id: 'l6-17', lessonId: 'lesson-6', vi: 'Đúng, anh ấy là bác sĩ.', ru: 'Верно, он врач.' },
  {
    id: 'l6-18',
    lessonId: 'lesson-6',
    vi: 'Không, anh ấy không phải là bác sĩ.',
    ru: 'Нет, он не врач.',
  },
  {
    id: 'l6-19',
    lessonId: 'lesson-6',
    vi: 'Không, anh không phải là bác sĩ.',
    ru: 'Нет, я не врач (мужчина называет себя anh).',
  },
  { id: 'l6-20', lessonId: 'lesson-6', vi: 'Chị ấy là y tá, phải không?', ru: 'Она медсестра, верно?' },
  {
    id: 'l6-21',
    lessonId: 'lesson-6',
    vi: 'Không, chị ấy không phải là y tá.',
    ru: 'Нет, она не медсестра.',
  },
  { id: 'l6-22', lessonId: 'lesson-6', vi: 'Chị ấy là cô giáo.', ru: 'Она учительница.' },
  { id: 'l6-23', lessonId: 'lesson-6', vi: 'Chị ấy có phải là cô giáo không?', ru: 'Она учительница?' },
  {
    id: 'l6-24',
    lessonId: 'lesson-6',
    vi: 'Chị ấy là cô giáo, phải không?',
    ru: 'Она учительница, верно?',
  },
  {
    id: 'l6-25',
    lessonId: 'lesson-6',
    vi: 'Em ấy là sinh viên, phải không?',
    ru: 'Она студентка, верно?',
  },
  {
    id: 'l6-26',
    lessonId: 'lesson-6',
    vi: 'Không, em ấy không phải là sinh viên.',
    ru: 'Нет, она не студентка.',
  },
  { id: 'l6-27', lessonId: 'lesson-6', vi: 'Em ấy là thư ký.', ru: 'Она секретарь.' },
  { id: 'l6-28', lessonId: 'lesson-6', vi: 'Em uống cà phê, phải không?', ru: 'Ты пьёшь кофе, верно?' },
  {
    id: 'l6-29',
    lessonId: 'lesson-6',
    vi: 'Em muốn ăn phở bò, phải không?',
    ru: 'Ты хочешь поесть фо бо, верно?',
  },
  {
    id: 'l6-30',
    lessonId: 'lesson-6',
    vi: 'Em đi Cam Ranh, phải không?',
    ru: 'Ты едешь в Камрань, верно?',
  },
  { id: 'l6-31', lessonId: 'lesson-6', vi: 'Em khỏe, phải không?', ru: 'Ты здоров, верно?' },
  { id: 'l6-32', lessonId: 'lesson-6', vi: 'Không, anh không thích cà phê.', ru: 'Нет, я не люблю кофе.' },
  {
    id: 'l6-33',
    lessonId: 'lesson-6',
    vi: 'Không, anh không muốn ăn phở bò.',
    ru: 'Нет, я не хочу есть фо бо.',
  },
  {
    id: 'l6-34',
    lessonId: 'lesson-6',
    vi: 'Không, anh không đi Cam Ranh.',
    ru: 'Нет, я не еду в Камрань.',
  },
];

export function getCardsForLesson(lessonId: string): FlashCard[] {
  return flashCards.filter((c) => c.lessonId === lessonId);
}
